#!/bin/bash


### this scripts expects ci_example_ros binary to be in ./bin folder
### this binary is compiled and copied there during install. See CMakeLists.txt for details

source /opt/ros/groovy/setup.bash 
roscore &
sleep 2
roscore_running=$(ps aux | grep roscore | grep opt)
if [ -z "$roscore_running" ]
then
    echo "failed to start roscore"
else
    
    echo "------ setting parameters -----"
    rosparam set gains_kp 1
    rosparam set gains_kd 1
    rosparam set gains_ki 1

    echo ""
    echo "------ CPP DEMO START ------"
    echo ""
    ./bin/ci_example_ros
    echo ""
    echo "------ DEMO END ------"
    echo ""


pkill roscore
fi

