#!/bin/bash

# this scripts expects ci_example_python_ros.py to be in <root>/demos/src 
# ci_example_python_ros_demo.py will need the PYTHONPATH updated with
# path to catkin libraries. This is done by sourcing <catkin workspace dir>/devel/setup.bash
# path to <catkin workspace dir>/devel/ should be given as first argument to the script
# for this to happen

path_to_devel=$1
source ${path_to_devel}/setup.bash

# trying to start roscore, exiting if failure to do so
roscore &
sleep 2
roscore_running=$(ps aux | grep roscore | grep opt)
if [ -z "$roscore_running" ]
then
    exit 1
fi

# setting parameters in ros parameter server
echo "------ setting parameters -----"
rosparam set kp 1
rosparam set kd 1
rosparam set ki 1

# if the next commands return error code, stopping roscore and exiting with error message
# if not implemented, the continuous integration script will not know the demo failed 
# (because python will return an error code, but not this script)
#trap "echo 'error detected on line: $LINENO' && echo 'python demo log: ' && cat ci_example_python_ros_demo.log && pkill roscore && exit 1" ERR EXIT

# running the python demo
echo ""
echo "------ PYTHON DEMO START ------"
echo ""
python ./src/ci_example_python_ros_demo.py 
success=$? # $? is the exit code of the latest command, here call to python
echo ""
echo "------ DEMO END ------"
echo ""

# stopping ros
pkill roscore

exit $success


