#!/bin/bash

### this scripts expects ci_example_python_ros.py to be in <root>/demos/src 
### note: before calling this script (and any script in the demos folder), the continuous integration script
### calls "source <root of catkin workspace>/devel/setup.bash" (from the root of the catkin workspace), which adds <root>/python/ci_example to the python path, which explains
### why imports in ci_example_python_ros.py are valid when this script is called

source /opt/ros/groovy/setup.bash 
roscore &
sleep 2
roscore_running=$(ps aux | grep roscore | grep opt)
if [ -z "$roscore_running" ]
then
    echo "failed to start roscore"
else
    
    echo "------ setting parameters -----"
    rosparam set gains_kp 1
    rosparam set gains_kd 1
    rosparam set gains_ki 1

    echo ""
    echo "------ PYTHON DEMO START ------"
    echo ""
    python ./python/ci_example_python_ros.py
    echo ""
    echo "------ DEMO END ------"
    echo ""

pkill roscore
fi

