#!/bin/bash

# this scripts expects ci_example_python_ros.py to be in <root>/demos/src 
# ci_example_python_ros_demo.py will need the PYTHONPATH updated with
# path to catkin libraries. This is done by sourcing <catkin workspace dir>/devel/setup.bash
# path to <catkin workspace dir>/devel/ should be given as first argument to the script
# for this to happen

path_to_devel=$1
source ${path_to_devel}/setup.bash

roscore &
sleep 2
roscore_running=$(ps aux | grep roscore | grep opt)
if [ -z "$roscore_running" ]
then
    echo "failed to start roscore"
else
    
    echo "------ setting parameters -----"
    rosparam set gains_kp 1
    rosparam set gains_kd 1
    rosparam set gains_ki 1

    echo ""
    echo "------ PYTHON DEMO START ------"
    echo ""
    python ./src/ci_example_python_ros_demo.py
    echo ""
    echo "------ DEMO END ------"
    echo ""

    exit 1

    pkill roscore
fi

