#! /bin/sh

# note: directly running this demo will not work: <root>/python/ci_example
# needs to be added to python path. This is done after:
# 1. "catkin_make" is called from the root of the catkin workspace
# 2. "source ./devel/setup.bash" is called from the root of the catkin workspace
# (the continuous integration script will do this automatically before executing this demo)


""":"
exec python $0 ${1+"$@"}
"""




from ci_example.pid import PID, get_default_pid, get_config_file_pid

current_position = 1
current_velocity = 0.1
position_target = 0
delta_time = 0.001

# basic example of PID usage
print "basic pid usage:"
class Configuration:
    def __init__(kp,kd,ki):
        self.kp,self.kd,self.ki=kp,kd,ki
config = Configuration(1,1,1)
pid = PID(config)
print pid
force = pid.compute(current_position,current_velocity,position_target,delta_time)
print "force:",force

# example of creation of PID using default gains
print "pid using default gains:"
pid = get_default_pid()
print pid
force = pid.compute(current_position,current_velocity,position_target,delta_time)
print "force:",force

# example of creation of PID using config files read from config file.
print "pid using gains read from config file:"
pid = get_config_file_pid(verbose=True)
print pid
force = pid.compute(current_position,current_velocity,position_target,delta_time)
print "force:",force
