#!/bin/bash

# to run (from anywhere) : "amd_clmc_get start ci_example_python"
# to run (from the catkin package root folder): ./start

# note: the script has to be executable, you may use: "chmod +x ./start"

source /opt/ros/groovy/setup.bash
cd "$( dirname "${BASH_SOURCE[0]}" )"
cd ../../../../../
catkin_make install
source ./devel/setup.bash

echo ""
echo "----------------------"
echo "running all unit test"
echo "----------------------"
echo ""
catkin_make run_tests

echo ""
echo "-----------------"
echo "running main demo"
echo "-----------------"
echo ""
cd "$( dirname "${BASH_SOURCE[0]}" )"
chmod +x ./demos/ci_example_python_demo
./demos/ci_example_python_demo

echo ""
echo "------------------------------"
echo "running demo that uses ROS"
echo "------------------------------"
echo ""
cd demos
chmod +x ./ci_example_ros_demo
./ci_example_ros_demo


echo ""
echo "--------"
echo "Done"
echo "--------"
echo ""

