#!/bin/bash

### this script is excepted to be in same folder as ci_example_ros_demo executable
### see CMakeLists.txt file to see how this is expected after calling "catkin_make install"

source /opt/ros/groovy/setup.bash 
roscore &
sleep 2
roscore_running=$(ps aux | grep roscore | grep opt)
if [ -z "$roscore_running" ]
then
    echo "failed to start roscore"
else
    
    echo "------ setting parameters -----"
    rosparam set gains_kp 1
    rosparam set gains_kd 1
    rosparam set gains_ki 1

    echo "------ DEMO START ------"
    ./ci_example_ros
    echo "------ DEMO END ------"

pkill roscore
fi

